/**
 * Static field definitions per entity, derived from JSON schemas.
 * Only includes meaningful user-facing fields (excludes publicId, tenantId, internal IDs).
 * Used for field-level permission configuration.
 */
export const ENTITY_FIELD_SCHEMAS = {
  Vessel: [
    { field: 'name', label: 'Name' },
    { field: 'imoNumber', label: 'IMO Number' },
    { field: 'mmsi', label: 'MMSI' },
    { field: 'callSign', label: 'Call Sign' },
    { field: 'vesselTypeRefId', label: 'Vessel Type' },
    { field: 'flagCountryId', label: 'Flag Country' },
    { field: 'ownerCompanyId', label: 'Owner Company' },
    { field: 'operatorCompanyId', label: 'Operator Company' },
    { field: 'yearBuilt', label: 'Year Built' },
    { field: 'shipyard', label: 'Shipyard' },
    { field: 'classSocietyCompanyId', label: 'Class Society' },
    { field: 'classNotation', label: 'Class Notation' },
    { field: 'gt', label: 'Gross Tonnage' },
    { field: 'dwt', label: 'Deadweight' },
    { field: 'loa_m', label: 'LOA (m)' },
    { field: 'beam_m', label: 'Beam (m)' },
    { field: 'cargoCapacity_m3', label: 'Cargo Capacity (m³)' },
    { field: 'status', label: 'Status' },
    { field: 'isActive', label: 'Is Active' },
    { field: 'image_url', label: 'Image URL' },
  ],
  Terminal: [
    { field: 'name', label: 'Name' },
    { field: 'terminalComplexId', label: 'Terminal Complex' },
    { field: 'countryId', label: 'Country' },
    { field: 'type', label: 'Type' },
    { field: 'status', label: 'Status' },
    { field: 'isActive', label: 'Is Active' },
    { field: 'notes', label: 'Notes' },
  ],
  Berth: [
    { field: 'name', label: 'Name' },
    { field: 'terminalId', label: 'Terminal' },
    { field: 'berthNumber', label: 'Berth Number' },
    { field: 'status', label: 'Status' },
    { field: 'isActive', label: 'Is Active' },
    { field: 'notes', label: 'Notes' },
  ],
  Document: [
    { field: 'title', label: 'Title' },
    { field: 'documentTypeId', label: 'Document Type' },
    { field: 'vesselId', label: 'Vessel' },
    { field: 'issueDate', label: 'Issue Date' },
    { field: 'expiryDate', label: 'Expiry Date' },
    { field: 'issuingAuthorityId', label: 'Issuing Authority' },
    { field: 'status', label: 'Status' },
    { field: 'fileUrl', label: 'File URL' },
    { field: 'notes', label: 'Notes' },
  ],
  DocumentType: [
    { field: 'name', label: 'Name' },
    { field: 'code', label: 'Code' },
    { field: 'categoryId', label: 'Category' },
    { field: 'description', label: 'Description' },
    { field: 'isActive', label: 'Is Active' },
  ],
  DocumentCategory: [
    { field: 'name', label: 'Name' },
    { field: 'description', label: 'Description' },
    { field: 'isActive', label: 'Is Active' },
  ],
  Company: [
    { field: 'name', label: 'Name' },
    { field: 'legalName', label: 'Legal Name' },
    { field: 'type', label: 'Type' },
    { field: 'countryId', label: 'Country' },
    { field: 'phone', label: 'Phone' },
    { field: 'email', label: 'Email' },
    { field: 'website', label: 'Website' },
    { field: 'iacsMember', label: 'IACS Member' },
    { field: 'isActive', label: 'Is Active' },
    { field: 'notes', label: 'Notes' },
  ],
  Contact: [
    { field: 'firstName', label: 'First Name' },
    { field: 'lastName', label: 'Last Name' },
    { field: 'email', label: 'Email' },
    { field: 'phoneMobile', label: 'Mobile Phone' },
    { field: 'phoneOffice', label: 'Office Phone' },
    { field: 'companyId', label: 'Company' },
    { field: 'jobTitle', label: 'Job Title' },
    { field: 'department', label: 'Department' },
    { field: 'dateOfBirth', label: 'Date of Birth' },
    { field: 'criticalRole', label: 'Critical Role' },
    { field: 'isActive', label: 'Is Active' },
    { field: 'notes', label: 'Notes' },
  ],
  Country: [
    { field: 'name', label: 'Name' },
    { field: 'iso2', label: 'ISO2 Code' },
    { field: 'iso3', label: 'ISO3 Code' },
    { field: 'isActive', label: 'Is Active' },
  ],
  IssuingAuthority: [
    { field: 'name', label: 'Name' },
    { field: 'countryId', label: 'Country' },
    { field: 'isActive', label: 'Is Active' },
  ],
  TerminalDocumentRequirement: [
    { field: 'terminalId', label: 'Terminal' },
    { field: 'documentTypeId', label: 'Document Type' },
    { field: 'isMandatory', label: 'Is Mandatory' },
    { field: 'validFrom', label: 'Valid From' },
    { field: 'notes', label: 'Notes' },
  ],
  TerminalRegistrationApplication: [
    { field: 'applicationNumber', label: 'Application Number' },
    { field: 'terminalId', label: 'Terminal' },
    { field: 'vesselId', label: 'Vessel' },
    { field: 'status', label: 'Status' },
    { field: 'documentApprovalMode', label: 'Document Approval Mode' },
    { field: 'notes', label: 'Notes' },
    { field: 'submittedAt', label: 'Submitted At' },
    { field: 'approvedAt', label: 'Approved At' },
    { field: 'rejectedAt', label: 'Rejected At' },
    { field: 'rejectionReason', label: 'Rejection Reason' },
  ],
  TerminalRegistrationChecklistItem: [
    { field: 'applicationId', label: 'Application' },
    { field: 'documentTypeId', label: 'Document Type' },
    { field: 'isMandatory', label: 'Is Mandatory' },
    { field: 'evaluationStatus', label: 'Evaluation Status' },
    { field: 'matchedVesselDocumentId', label: 'Matched Document' },
    { field: 'comments', label: 'Comments' },
  ],
  VesselCompatibility: [
    { field: 'vesselId', label: 'Vessel' },
    { field: 'terminalId', label: 'Terminal' },
    { field: 'berthId', label: 'Berth' },
    { field: 'compatibilityStatus', label: 'Compatibility Status' },
    { field: 'notes', label: 'Notes' },
  ],
  VesselTerminalDocumentSet: [
    { field: 'name', label: 'Name' },
    { field: 'vesselId', label: 'Vessel' },
    { field: 'terminalId', label: 'Terminal' },
    { field: 'isActive', label: 'Is Active' },
  ],
  VesselTerminalDocumentSetItem: [
    { field: 'documentSetId', label: 'Document Set' },
    { field: 'documentTypeId', label: 'Document Type' },
    { field: 'isMandatory', label: 'Is Mandatory' },
  ],
  ApplicationUser: [
    { field: 'full_name', label: 'Full Name' },
    { field: 'email', label: 'Email' },
    { field: 'username', label: 'Username' },
    { field: 'status', label: 'Status' },
    { field: 'notes', label: 'Notes' },
  ],
  ApplicationRole: [
    { field: 'role_name', label: 'Role Name' },
    { field: 'description', label: 'Description' },
    { field: 'is_active', label: 'Is Active' },
  ],
  ApplicationUserRole: [
    { field: 'application_user_id', label: 'User' },
    { field: 'application_role_id', label: 'Role' },
    { field: 'assigned_from', label: 'Assigned From' },
    { field: 'active', label: 'Active' },
    { field: 'valid_from', label: 'Valid From' },
    { field: 'valid_to', label: 'Valid To' },
  ],
  WorkflowDefinition: [
    { field: 'workflow_name', label: 'Workflow Name' },
    { field: 'table_name', label: 'Target Entity' },
    { field: 'description', label: 'Description' },
    { field: 'is_active', label: 'Is Active' },
  ],
  WorkflowStatus: [
    { field: 'status_name', label: 'Status Name' },
    { field: 'status_code', label: 'Status Code' },
    { field: 'color_code', label: 'Color Code' },
    { field: 'is_initial', label: 'Is Initial' },
    { field: 'is_final', label: 'Is Final' },
    { field: 'sort_order', label: 'Sort Order' },
  ],
  WorkflowAction: [
    { field: 'action_name', label: 'Action Name' },
    { field: 'action_code', label: 'Action Code' },
    { field: 'description', label: 'Description' },
    { field: 'sort_order', label: 'Sort Order' },
  ],
  WorkflowTransition: [
    { field: 'from_status_id', label: 'From Status' },
    { field: 'to_status_id', label: 'To Status' },
    { field: 'workflow_action_id', label: 'Triggered By Action' },
    { field: 'is_active', label: 'Is Active' },
  ],
  CompanySecurityPolicy: [
    { field: 'authSourcePolicy', label: 'Auth Source Policy' },
    { field: 'mfaSourcePolicy', label: 'MFA Source Policy' },
    { field: 'enforceMfa', label: 'Enforce MFA' },
    { field: 'passwordMinLength', label: 'Min Password Length' },
    { field: 'passwordComplexity', label: 'Password Complexity' },
    { field: 'sessionTimeoutMinutes', label: 'Session Timeout (min)' },
    { field: 'isActive', label: 'Is Active' },
  ],
  CompanyIdentityProvider: [
    { field: 'name', label: 'Name' },
    { field: 'protocol', label: 'Protocol' },
    { field: 'isActive', label: 'Is Active' },
  ],
  CompanyGroupRoleMapping: [
    { field: 'groupName', label: 'Group Name' },
    { field: 'applicationRoleId', label: 'Application Role' },
  ],
  SystemAuditLog: [
    { field: 'module_name', label: 'Module' },
    { field: 'entity_name', label: 'Entity' },
    { field: 'action_type', label: 'Action Type' },
    { field: 'changed_by', label: 'Changed By' },
    { field: 'changed_at', label: 'Changed At' },
  ],
  ApplicationFunction: [
    { field: 'function_name', label: 'Function Name' },
    { field: 'function_key', label: 'Function Key' },
    { field: 'module_name', label: 'Module' },
    { field: 'description', label: 'Description' },
    { field: 'is_active', label: 'Is Active' },
  ],
};