import React, { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { MessageSquare, X, Send, Bot } from 'lucide-react';
import { getChatbotResponse } from '@/components/services/chatbotService';
import { useChatbotContext } from '@/components/chatbot/ChatbotProvider';
import ReactMarkdown from 'react-markdown';

/**
 * Embedded Chatbot Widget
 *
 * PURPOSE:
 * A self-contained, offline chatbot UI that provides contextual help to users.
 * It lives in the main application layout and is available on all pages.
 *
 * OFFLINE & RULE-BASED:
 * This component is intentionally simple. It does NOT connect to any external
 * AI service. All responses are generated by the `chatbotService`, which uses
 * a rule-based system and content stored in the application's own database
 * (HelpIntent, HelpAlias, etc.). This ensures functionality is fully exportable
 * and requires no ongoing subscription costs or network access for support.
 *
 * ---
 *
 * STATE MANAGEMENT:
 * - `isOpen`: Controls the visibility of the chat panel.
 * - `messages`: An array of chat messages, each with a `sender` ('user' or 'bot')
 *   and `text` content.
 * - `inputValue`: The current text in the user input field.
 *
 * ---
 *
 * USER INTERACTION FLOW:
 *
 * 1. `handleSendMessage`:
 *    - Triggered when the user sends a message.
 *    - Adds the user's message to the `messages` array.
 *    - Clears the input field.
 *    - Calls the `chatbotService.getChatbotResponse` function, passing the
 *      user's input and the current `pageKey` from the `ChatbotContext`.
 *
 * 2. `getChatbotResponse` (in `chatbotService.js`):
 *    - This is the "brain" of the chatbot. It matches the input against `HelpAlias`
 *      records and uses `HelpContextRule` and `HelpIntent` priority to find the
 *      best answer.
 *
 * 3. RESPONSE HANDLING:
 *    - If the service returns a valid intent, a bot message is created with
 *      the `answerMarkdown`.
 *    - If no intent is found, a default "I don't understand" message is shown.
 *    - The response is added to the `messages` array, triggering a re-render.
 *
 * ---
 *
 * CONTEXT AWARENESS:
 * - `const { pageKey } = useChatbotContext();`
 * - This hook retrieves the current page identifier (e.g., 'VesselDetail')
 *   set by the parent page.
 * - The `pageKey` is crucial for allowing the `chatbotService` to provide
 *   contextually relevant answers. It is the primary mechanism that makes the
 *   chatbot "smart" without being an actual AI.
 *
 * ---
 *
 * ACTION BUTTONS (Future Enhancement Placeholder):
 * The `HelpIntent` entity includes `actionType` and `actionPayload` fields.
 * While the data model is in place, this UI component does not yet render
 * interactive buttons.
 *
 * // TODO: Implement rendering of action buttons based on `bestIntent.actionType`.
 * // This would involve creating a button that, when clicked, performs an
 * // internal navigation or opens a modal (e.g., `navigate(payload.page)`).
 * // This keeps all actions internal to the application.
 */
export default function ChatbotWidget() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const { pageKey } = useChatbotContext();
  const messagesEndRef = useRef(null);

  useEffect(() => {
    if (isOpen && messages.length === 0) {
      setMessages([
        {
          sender: 'bot',
          text: `Hello! I'm the ${"Portunus"} Assistant. How can I help you today? You can ask me about registration, documents, or terminal compatibility.`,
        },
      ]);
    }
  }, [isOpen]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSendMessage = async () => {
    if (inputValue.trim() === '') return;

    const userMessage = { sender: 'user', text: inputValue };
    setMessages(prev => [...prev, userMessage]);
    setInputValue('');

    const bestIntent = await getChatbotResponse(inputValue, pageKey);

    let botResponse;
    if (bestIntent) {
      botResponse = { sender: 'bot', text: bestIntent.answerMarkdown };
    } else {
      botResponse = {
        sender: 'bot',
        text: "I'm sorry, I don't have information on that. Please try rephrasing your question, or ask me about topics like 'registration', 'documents', or 'terminal statuses'.",
      };
    }

    setMessages(prev => [...prev, botResponse]);
  };

  return (
    <>
      <div className="fixed bottom-6 right-6 z-50">
        <Button
          onClick={() => setIsOpen(!isOpen)}
          className="rounded-full w-16 h-16 bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-lg hover:scale-110 transition-transform"
        >
          {isOpen ? <X size={28} /> : <MessageSquare size={28} />}
        </Button>
      </div>

      {isOpen && (
        <div className="fixed bottom-24 right-6 z-50 w-full max-w-sm">
          <Card className="flex flex-col h-[60vh] shadow-2xl border-gray-300">
            <CardHeader className="bg-gray-100 border-b">
              <CardTitle className="flex items-center gap-2 text-gray-800">
                <Bot />
                Support Assistant
              </CardTitle>
            </CardHeader>
            <CardContent className="flex-1 overflow-y-auto p-4 space-y-4">
              {messages.map((msg, index) => (
                <div
                  key={index}
                  className={`flex gap-2 ${
                    msg.sender === 'user' ? 'justify-end' : 'justify-start'
                  }`}
                >
                  <div
                    className={`max-w-[80%] rounded-2xl px-4 py-2.5 ${
                      msg.sender === 'user'
                        ? 'bg-blue-600 text-white'
                        : 'bg-gray-200 text-gray-800'
                    }`}
                  >
                    <ReactMarkdown className="prose prose-sm max-w-none">
                      {msg.text}
                    </ReactMarkdown>
                  </div>
                </div>
              ))}
              <div ref={messagesEndRef} />
            </CardContent>
            <div className="p-4 border-t bg-white">
              <div className="flex gap-2">
                <Input
                  value={inputValue}
                  onChange={e => setInputValue(e.target.value)}
                  onKeyPress={e => e.key === 'Enter' && handleSendMessage()}
                  placeholder="Ask a question..."
                  className="flex-1"
                />
                <Button onClick={handleSendMessage} className="bg-blue-600 hover:bg-blue-700">
                  <Send size={18} />
                </Button>
              </div>
            </div>
          </Card>
        </div>
      )}
    </>
  );
}